<a href="https://colab.research.google.com/github/AshishSiwach/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

### Vectors
One dimensional arrays

In [ ]:
# Creating a row vector
vec_row = np.array([2, 4, 6])
# Creating a column vector
vec_col = np.array([[2], [4], [6]])

In [ ]:
vec_row

array([2, 4, 6])

In [ ]:
vec_col

array([[2],
       [4],
       [6]])

In [ ]:
# Creating a two dimensional array
matrix = np.array([
                   [1, 2, 3],
                   [4, 5, 6]
])
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

(2, 3)

Matrix has two rows and three columns

In [ ]:
# Creating a three dimensional array
arr_3d = np.array([
                   [
                    [1, 2, 3],
                    [4, 5, 6]
                   ],
                   [
                    [7, 8, 9],
                    [10, 11, 12]
                   ]
])
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr_3d.ndim # Number of dimensions of an array

3

In [ ]:
arr_3d.shape # returns a tuple containing number of rows and columns in an array
# So two matrices with two rows and three columns

(2, 2, 3)

In [ ]:
arr_3d.size # number of elements in an array

12

### Other ways of creating numpy arrays

In [ ]:
np.ones((3, 4)) # array of ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3, 2)) # array of zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.random.randn(2, 3)
# Returns samples from a standard normal distribution

array([[-1.34644181,  0.48739575, -0.80845776],
       [-0.90871336, -0.84533754,  0.57042127]])

In [ ]:
np.random.rand(2, 3)
# Returns samples from a uniform distribution

array([[0.45272466, 0.78655902, 0.34543591],
       [0.38911113, 0.6401906 , 0.58982325]])

In [ ]:
np.random.randint(low = 0, high = 100, size = (2, 3))
# Return random integers from `low` (inclusive)
# to `high` (exclusive).

# Return random integers from the "discrete uniform"
# distribution

array([[34, 25, 40],
       [65, 61, 29]])

In [ ]:
np.arange(7, 71, 7) # params start, stop and step size

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [ ]:
np.linspace(7, 70, 10)
# Return evenly spaced numbers over a specified interval.
# start,
#    stop,
#    num=50,
#    endpoint=True,
#    retstep=False,
#    dtype=None,
#    axis=0,
# Returns `num` evenly spaced samples, calculated over the
# interval [`start`, `stop`].

# The endpoint of the interval can optionally be excluded.

array([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70.])

In [ ]:
# array of Booleans
np.array([True, False, True, True])

array([ True, False,  True,  True])

In [ ]:
str_arr = ['a', 'b', 'c'] # array with string data type elements
str_arr

['a', 'b', 'c']

In [ ]:
st_arr = ['1.1', '1.02', '2.21']
# Convert the arr to float data type elements
arr = np.array(st_arr, dtype = 'float')
print(arr)
print(arr.dtype)

[1.1  1.02 2.21]
float64


### Indexing

In [ ]:
vec_row = np.array([2, 4, 6])
vec_row[0]

2

In [ ]:
vec_row[1]

4

In [ ]:
vec_row[2]

6

In [ ]:
matrix = np.array([
                   [1, 2, 3],
                   [4, 5, 6]
])
print(matrix[0, 0]) # first row and first column
print(matrix[1, 2]) # second row and third column
print(matrix[1, 1]) # second row and second column

1
6
5


In [ ]:
print(matrix[:, :])
print(matrix[:, 0:2])
print(matrix[0:1, :])

[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]
[[1 2 3]]


In [ ]:
arr_3d = np.array([
                   [
                    [1, 2, 3],
                    [4, 5, 6]
                   ],
                   [
                    [7, 8, 9],
                    [10, 11, 12]
                   ]
])
print(arr_3d[0, 0, 0]) # first matrix first row and first column
print(arr_3d[1, 0, 0]) # second matrix first row and first column
print(arr_3d[0, 1, 2]) # first matrix second row and third column

1
7
6


In [ ]:
print('first matrix: ',arr_3d[0, :, :]) # gives first matrix
print('second matrix: ',arr_3d[1, :, :]) # gives second matrix
print('elements in second row of both matrices: ',arr_3d[:, 1, :]) # gives elements in the second row of both matrices
print('first and second column elements: ',arr_3d[:, :, 0:2]) # gives elements in first and second column of both matrices

first matrix:  [[1 2 3]
 [4 5 6]]
second matrix:  [[ 7  8  9]
 [10 11 12]]
elements in second row of both matrices:/n  [[ 4  5  6]
 [10 11 12]]
first and second column elements:  [[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


In [ ]:
# accessing even numbers in the array
arr_3d[arr_3d % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
# accessing even numbers divisible by 3
arr_3d[(arr_3d % 2 == 0) & (arr_3d % 3 == 0)]

array([ 6, 12])

In [ ]:
# Substitute value of an element in an array
arr_3d[0, 1, 1] = 16
arr_3d

array([[[ 1,  2,  3],
        [ 4, 16,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### Numpy Operations

In [ ]:
mat1 = np.random.rand(3, 4)
mat2 = np.random.rand(3, 4)
print('mat1: ',mat1)
print('mat2: ',mat2)

mat1:  [[0.84430352 0.40143353 0.9573767  0.66129807]
 [0.00121679 0.90742976 0.09750756 0.31092596]
 [0.80455049 0.29525565 0.38506223 0.66763424]]
mat2:  [[0.57804876 0.30687658 0.62419886 0.60154142]
 [0.38016187 0.47156864 0.42231672 0.71208139]
 [0.30145794 0.70278915 0.30136593 0.3305465 ]]


In [ ]:
mat1 + mat2 # element wise addition

array([[1.33802493, 1.08627247, 0.44296226, 0.50342227],
       [1.30536674, 1.21642606, 1.0155881 , 1.035474  ],
       [0.83473501, 1.60761911, 1.21016533, 1.04563627]])

In [ ]:
mat1 - mat2 # element wise subtraction

array([[ 0.20994996, -0.02056887,  0.13852449, -0.01034445],
       [-0.20749007, -0.0948804 , -0.2513629 , -0.87711686],
       [-0.81819308,  0.33391344,  0.76065273, -0.42480374]])

In [ ]:
mat1 * mat2 # element wise multiplication

array([[4.88048599e-01, 1.23190549e-01, 5.97593443e-01, 3.97798182e-01],
       [4.62576859e-04, 4.27915416e-01, 4.11790726e-02, 2.21404588e-01],
       [2.42538132e-01, 2.07502465e-01, 1.16044638e-01, 2.20684159e-01]])

In [ ]:
mat1/mat2 # element wise division

array([[1.46060951, 1.30812694, 1.53376874, 1.09933921],
       [0.00320071, 1.92427927, 0.23088728, 0.43664385],
       [2.66886486, 0.42011981, 1.27772318, 2.01978916]])

In [ ]:
# Finding maximum and minimum values in an array
np.max(mat1)

0.9573766967294046

In [ ]:
np.min(mat2)

0.3013659305226546

In [ ]:
# Finding max and min elements in each row and column of a matrix
print('max in each column: ', np.max(mat1, axis = 0))
print('min in each column: ', np.min(mat1, axis = 0))
print('max in each row: ', np.max(mat1, axis = 1))
print('min in each row: ', np.min(mat1, axis = 1))

max in each column:  [0.84430352 0.90742976 0.9573767  0.66763424]
min in each column:  [0.00121679 0.29525565 0.09750756 0.31092596]
max in each row:  [0.9573767  0.90742976 0.80455049]
min in each row:  [0.40143353 0.00121679 0.29525565]


In [ ]:
# Adding values in each row and column of a matrix
print(np.sum(mat1, axis = 0)) # adding elements in a column
print(np.sum(mat1, axis = 1)) # adding element in a row

[1.6500708  1.60411893 1.43994649 1.63985827]
[2.86441181 1.31708006 2.15250261]


### Broadcasting

In [2]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [3]:
arr.reshape(4, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [6]:
arr = np.arange(24)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [7]:
arr.reshape(6, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
arr.reshape(3, 2, 4) # three matrices of two rows and 4 columns

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [9]:
arr1 = np.arange(6)
arr2 = np.arange(5) # 1 row and 5 columns
arr1.reshape(6, 1) + arr2
# 1 row of second vector can be broadcasted to 6 rows and 1 column of first vector can be broadcasted to 5 columns

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8],
       [5, 6, 7, 8, 9]])

In [11]:
arr = np.arange(60).reshape(3, 4, 5)
arr1 = np.ones((4, 1))
arr + arr1
# Missing dimension 3 is broadcasted to 3
# 1 column is broadcasted to 5
# Only 1 and missing dimensions can be broadcasted to make dimensions compatible

array([[[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.],
        [16., 17., 18., 19., 20.]],

       [[21., 22., 23., 24., 25.],
        [26., 27., 28., 29., 30.],
        [31., 32., 33., 34., 35.],
        [36., 37., 38., 39., 40.]],

       [[41., 42., 43., 44., 45.],
        [46., 47., 48., 49., 50.],
        [51., 52., 53., 54., 55.],
        [56., 57., 58., 59., 60.]]])

In [12]:
mat1 = np.random.rand(3, 4)
mat2 = np.random.rand(1, 4)
mat1 * mat2
# normal asterisk multiplication is carried out by multiplying corresponding elements in two matrices
# eg multiplying a[i][j] with b[i][j]
# it works by broadcasting dimensions of two arrays

array([[0.61106367, 0.70323866, 0.08413558, 0.21581675],
       [0.56818121, 0.79110299, 0.01860002, 0.3173132 ],
       [0.21312227, 0.42836516, 0.16964318, 0.02990508]])

In [14]:
# dot product is matrix multiplication where no. of columns of first matrix should be equal to no. of rows of second matrix
np.dot(mat1, mat2.reshape(4, 1))

array([[1.61425466],
       [1.69519742],
       [0.84103568]])

In [16]:
# https://www.geeksforgeeks.org/difference-between-numpy-dot-and-operation-in-python/
a1 = np.array([
               [10, 20],
               [20, 40]
])
a2 = np.array([
               [5, 10],
               [10, 10]
])
print('asterisk element wise multiplication')
print(a1 * a2)
print('dot product')
print(np.dot(a1, a2))
print('dot product can also be done using @ symbol')
print(a1 @ a2)

asterisk element wise multiplication
[[ 50 200]
 [200 400]]
dot product
[[250 300]
 [500 600]]
dot product can also be done using @ symbol
[[250 300]
 [500 600]]


In [18]:
# Flatten a matrix
m1 = np.arange(12).reshape(4, 3)
print(m1.flatten())
print(m1.reshape(1, -1)) # one row and any number of columns

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]


In [17]:
# Taking transpose of a matrix
m1 = np.arange(6).reshape(3, 2)
print('matrix')
print(m1)
print('Transpose of a matrix')
print(m1.T)

matrix
[[0 1]
 [2 3]
 [4 5]]
Transpose of a matrix
[[0 2 4]
 [1 3 5]]


In [19]:
# Taking inverse of a matrix
m = np.array([
              [1, 2],
              [3, 4]
])
m_inverse = np.linalg.inv(m) 
# multiplication of a matrix with its inverse gives identity matrix
i = np.dot(m, m_inverse)
print('matrix')
print(m)
print('Inverse of a matrix')
print(m_inverse)
print('multiplication of a matrix with its inverse')
print(i)

matrix
[[1 2]
 [3 4]]
Inverse of a matrix
[[-2.   1. ]
 [ 1.5 -0.5]]
multiplication of a matrix with its inverse
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


## Stats with Numpy

In [4]:
arr = np.arange(1, 10).reshape(3, 3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.max(arr) # np.max is an alias of np.amax, they both do same thing

9

In [10]:
np.min(arr)

1

In [12]:
np.mean(arr)

5.0

In [13]:
np.var(arr)

6.666666666666667

In [14]:
np.std(arr)

2.581988897471611

In [15]:
np.median(arr)

5.0

In [16]:
np.percentile(arr, 50) # returns median

5.0

In [17]:
np.percentile(arr, 25) # returns median of first half of numbers

3.0

In [18]:
np.percentile(arr, 75) # returns median of second half of numbers

7.0

In [19]:
# Compute interquartile range
iqr = np.percentile(arr, 75) - np.percentile(arr, 25)
iqr

4.0

In [20]:
z_score = (arr - np.mean(arr))/np.std(arr)
z_score

array([[-1.54919334, -1.161895  , -0.77459667],
       [-0.38729833,  0.        ,  0.38729833],
       [ 0.77459667,  1.161895  ,  1.54919334]])

In [22]:
# Concatenating arrays
a1 = np.arange(6).reshape(3, 2)
a2 = np.arange(6, 12).reshape(3, 2)
np.concatenate((a1, a2), axis = 0)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [23]:
a1 = np.arange(6).reshape(3, 2)
a2 = np.arange(6, 12).reshape(3, 2)
np.concatenate((a1, a2), axis = 1)

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [25]:
np.vstack((a1, a2)) # stacks arrays row wise same as concatenating with axis = 0

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [26]:
np.hstack((a1, a2)) # stacks arrays column wise same as concatenating with axis = 1

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])